### ISSUE TITLE
Enable action on Windows and macOS

### ISSUE THREAD

**Issue by MiSikora** [ffurrer2/extract-release-notes#1]
Since this action is Docker-based it can run only on Linux. Would there be an interest to change it to a JS one in order to enable it on other platforms?

I can make a PR but I'd like to know beforehand if there's an interest or should I write a different action.

**Comment by ffurrer2** [comment]
Hi @MiSikora,

I reimplemented the action in JS and added macos-11.0 and windows-2019 to the test matrix. 

Can you have a look at the new v1.4.0-rc.1 release?

**Comment by MiSikora** [comment]
Wow, thanks for the quick update. I'll check it soon.

**Comment by MiSikora** [comment]
Yup, I can confirm that it works on all platforms. Thanks once again!
