### ISSUE TITLE
Support Unreleased section for pre-release builds

### ISSUE THREAD

**Issue by richardmatsu** [ffurrer2/extract-release-notes#125]
It would be nice if the action were to extract the content between the first and second H2 if a parameter such as `prerelease: true` were set.

For example,

```
- name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        prerelease: ${{ env.PRERELEASE }}
```

This would interact nicely with `actions/upload-release-asset`.

**Comment by rkleinman-hpe** [comment]
Just ran into this today, would be great to have.

**Comment by rkleinman-hpe** [comment]
Awesome, thanks!
