### ISSUE TITLE
Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by tiamed** [ffurrer2/extract-release-notes#288]
https://github.com/ffurrer2/extract-release-notes/blob/9237796aff72c21dcf921e825b79e04b3ec90657/src/index.js#L57

<img width="628" alt="image" src="https://github.com/ffurrer2/extract-release-notes/assets/20151080/51bebaad-7e9b-4fdd-bc2d-047b5070fdab">

**Comment by jacobszpz** [comment]
Surround your version numbers with []

**Comment by vmsaif** [comment]
I am having this issue. 

This is my CHANGELOG.md

```
# Changelog

All notable changes to this project will be documented in this file.

## [Unreleased]

## [v1.1.0] - 2023-09-03

### Added

- added reset button to reset the game

## [v1.0.0] - 2023-09-03

### Added

- Initial release.
```

in my workflow
```
    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v1.17.0
```

error:
```
Run ffurrer2/extract-release-notes@v1.8.0
Error: Reduce of empty array with no initial value
```

**Comment by jacobszpz** [comment]
I believe you arent supposed to have v before the version numbers
