### ISSUE TITLE
Support writing the outputs into files

### ISSUE THREAD

**Issue by Goooler** [ffurrer2/extract-release-notes#350]
Now GH CLI supports releasing like

```sh
gh release create --title ${{ github.ref_name }} --notes-file release_notes.txt
```

It would be great if we could generate an output file for GH to use, I know we can do it like

```sh
echo "${{ steps.extract-release-notes.outputs.release_notes }}" > release_notes.txt
```

but some case have to be covered in #349.

**Comment by Goooler** [comment]
Seems this is optional, I miss-used the output with double quotations, it should be:

```sh
echo '${{ steps.extract-release-notes.outputs.release_notes }}' > release_notes.txt
```

here for writing the note file.

**Comment by ffurrer2** [comment]
Hi @Goooler, have you tried the `release_notes_file` parameter?  With this parameter it should be possible to write the release notes to a file.

**Comment by Goooler** [comment]
Ooops, I missed that, it works for me now.

Thanks!
